// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiChainData, ApiChainResponses, ApiDeleteSnapshotData, ApiDeleteSnapshotErrors, ApiDeleteSnapshotResponses, ApiGameData, ApiGameDeleteData, ApiGameDeleteErrors, ApiGameDeleteResponses, ApiGameDraftData, ApiGameDraftErrors, ApiGameDraftResponses, ApiGameErrors, ApiGameResponses, ApiGameSaveData, ApiGameSaveErrors, ApiGameSaveResponses, ApiNotionFetchData, ApiNotionFetchErrors, ApiNotionFetchResponses, ApiPlayerCheckSimilarityData, ApiPlayerCheckSimilarityErrors, ApiPlayerCheckSimilarityResponses, ApiPlayerGetAllData, ApiPlayerGetAllResponses, ApiPlayerLookupData, ApiPlayerLookupErrors, ApiPlayerLookupResponses, ApiPlayerRenameData, ApiPlayerRenameErrors, ApiPlayerRenameResponses, ApiRunNotionSyncData, ApiRunNotionSyncErrors, ApiRunNotionSyncResponses, ApiSnapshotData, ApiSnapshotErrors, ApiSnapshotResponses, ApiSnapshotSaveData, ApiSnapshotSaveErrors, ApiSnapshotSaveResponses, ApiSyncStatusData, ApiSyncStatusResponses, CatchAllData, CatchAllErrors, CatchAllResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Api Chain
 *
 * Returns the full chain tree for the timeline view.
 */
export const apiChain = <ThrowOnError extends boolean = false>(options?: Options<ApiChainData, ThrowOnError>) => (options?.client ?? client).get<ApiChainResponses, unknown, ThrowOnError>({ url: '/api/chain', ...options });

/**
 * Api Delete Snapshot
 *
 * Deletes a snapshot and all its dependent snapshots/events.
 */
export const apiDeleteSnapshot = <ThrowOnError extends boolean = false>(options: Options<ApiDeleteSnapshotData, ThrowOnError>) => (options.client ?? client).delete<ApiDeleteSnapshotResponses, ApiDeleteSnapshotErrors, ThrowOnError>({ url: '/api/snapshot/{snapshot_id}', ...options });

/**
 * Api Snapshot
 *
 * Returns snapshot metadata + player list for the detail panel.
 */
export const apiSnapshot = <ThrowOnError extends boolean = false>(options: Options<ApiSnapshotData, ThrowOnError>) => (options.client ?? client).get<ApiSnapshotResponses, ApiSnapshotErrors, ThrowOnError>({ url: '/api/snapshot/{snapshot_id}', ...options });

/**
 * Api Snapshot Save
 *
 * Unified endpoint to save a new snapshot from a player list.
 * Returns: {"snapshot_id": <new_id>}
 */
export const apiSnapshotSave = <ThrowOnError extends boolean = false>(options: Options<ApiSnapshotSaveData, ThrowOnError>) => (options.client ?? client).post<ApiSnapshotSaveResponses, ApiSnapshotSaveErrors, ThrowOnError>({
    url: '/api/snapshot/save',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Notion Fetch
 *
 * Fetches raw player data from the local notion_cache table.
 * Returns: {"players": [...], "similar_names": [...], "last_updated": "..."}
 */
export const apiNotionFetch = <ThrowOnError extends boolean = false>(options: Options<ApiNotionFetchData, ThrowOnError>) => (options.client ?? client).post<ApiNotionFetchResponses, ApiNotionFetchErrors, ThrowOnError>({
    url: '/api/snapshot/notion/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Game
 *
 * Returns full game event detail for the detail panel.
 */
export const apiGame = <ThrowOnError extends boolean = false>(options: Options<ApiGameData, ThrowOnError>) => (options.client ?? client).get<ApiGameResponses, ApiGameErrors, ThrowOnError>({ url: '/api/game/{game_event_id}', ...options });

/**
 * Api Game Delete
 *
 * Delete a game and its output snapshot, with optional squash on parent.
 */
export const apiGameDelete = <ThrowOnError extends boolean = false>(options: Options<ApiGameDeleteData, ThrowOnError>) => (options.client ?? client).delete<ApiGameDeleteResponses, ApiGameDeleteErrors, ThrowOnError>({ url: '/api/game/{game_id}', ...options });

/**
 * Api Game Draft
 *
 * Generates a draft of game tables without saving to the database.
 * Returns: DraftResult as dict
 */
export const apiGameDraft = <ThrowOnError extends boolean = false>(options: Options<ApiGameDraftData, ThrowOnError>) => (options.client ?? client).post<ApiGameDraftResponses, ApiGameDraftErrors, ThrowOnError>({
    url: '/api/game/draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Game Save
 *
 * Saves a confirmed game draft to the database.
 * Supports both creating new games and updating existing games in-place.
 * Returns: {"game_id": int}
 */
export const apiGameSave = <ThrowOnError extends boolean = false>(options: Options<ApiGameSaveData, ThrowOnError>) => (options.client ?? client).post<ApiGameSaveResponses, ApiGameSaveErrors, ThrowOnError>({
    url: '/api/game/save',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Player Rename
 *
 * Rename a player in the players table.
 * Returns: {"success": true} or error
 */
export const apiPlayerRename = <ThrowOnError extends boolean = false>(options: Options<ApiPlayerRenameData, ThrowOnError>) => (options.client ?? client).post<ApiPlayerRenameResponses, ApiPlayerRenameErrors, ThrowOnError>({
    url: '/api/player/rename',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Player Get All
 *
 * Get all known players. Returns rich, unformatted objects to power UI autocomplete.
 */
export const apiPlayerGetAll = <ThrowOnError extends boolean = false>(options?: Options<ApiPlayerGetAllData, ThrowOnError>) => (options?.client ?? client).get<ApiPlayerGetAllResponses, unknown, ThrowOnError>({ url: '/api/player/all', ...options });

/**
 * Api Player Lookup
 *
 * Targeted deep history lookup. Prioritizes notion_id if provided.
 */
export const apiPlayerLookup = <ThrowOnError extends boolean = false>(options: Options<ApiPlayerLookupData, ThrowOnError>) => (options.client ?? client).post<ApiPlayerLookupResponses, ApiPlayerLookupErrors, ThrowOnError>({
    url: '/api/player/lookup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Player Check Similarity
 *
 * Checks a list of names for typos against the NotionCache.
 */
export const apiPlayerCheckSimilarity = <ThrowOnError extends boolean = false>(options: Options<ApiPlayerCheckSimilarityData, ThrowOnError>) => (options.client ?? client).post<ApiPlayerCheckSimilarityResponses, ApiPlayerCheckSimilarityErrors, ThrowOnError>({
    url: '/api/player/check-similarity',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Run Notion Sync
 *
 * Enqueues notion_sync to run in the background.
 * Returns immediately with success message.
 */
export const apiRunNotionSync = <ThrowOnError extends boolean = false>(options: Options<ApiRunNotionSyncData, ThrowOnError>) => (options.client ?? client).post<ApiRunNotionSyncResponses, ApiRunNotionSyncErrors, ThrowOnError>({
    url: '/api/run/notion_sync',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Sync Status
 *
 * Returns the current status of the background Notion sync daemon.
 */
export const apiSyncStatus = <ThrowOnError extends boolean = false>(options?: Options<ApiSyncStatusData, ThrowOnError>) => (options?.client ?? client).get<ApiSyncStatusResponses, unknown, ThrowOnError>({ url: '/api/sync/status', ...options });

/**
 * Catch All
 *
 * Serve the Svelte SPA for any route.
 */
export const catchAll = <ThrowOnError extends boolean = false>(options: Options<CatchAllData, ThrowOnError>) => (options.client ?? client).get<CatchAllResponses, CatchAllErrors, ThrowOnError>({ url: '/{full_path}', ...options });
