// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  ApiAddPlayerData,
  ApiAddPlayerErrors,
  ApiAddPlayerResponses,
  ApiChainData,
  ApiChainResponses,
  ApiCreateSnapshotData,
  ApiCreateSnapshotErrors,
  ApiCreateSnapshotResponses,
  ApiCreateSnapshotRootData,
  ApiCreateSnapshotRootErrors,
  ApiCreateSnapshotRootResponses,
  ApiDeleteSnapshotData,
  ApiDeleteSnapshotErrors,
  ApiDeleteSnapshotResponses,
  ApiGameData,
  ApiGameDeleteData,
  ApiGameDeleteErrors,
  ApiGameDeleteResponses,
  ApiGameDraftData,
  ApiGameDraftErrors,
  ApiGameDraftResponses,
  ApiGameErrors,
  ApiGameResponses,
  ApiGameSaveData,
  ApiGameSaveErrors,
  ApiGameSaveResponses,
  ApiNotionFetchData,
  ApiNotionFetchErrors,
  ApiNotionFetchResponses,
  ApiPlayerCheckSimilarityData,
  ApiPlayerCheckSimilarityErrors,
  ApiPlayerCheckSimilarityResponses,
  ApiPlayerGetAllData,
  ApiPlayerGetAllResponses,
  ApiPlayerLookupData,
  ApiPlayerLookupErrors,
  ApiPlayerLookupResponses,
  ApiPlayerRenameData,
  ApiPlayerRenameErrors,
  ApiPlayerRenameResponses,
  ApiRunData,
  ApiRunErrors,
  ApiRunNotionSyncData,
  ApiRunNotionSyncErrors,
  ApiRunNotionSyncResponses,
  ApiRunResponses,
  ApiSnapshotData,
  ApiSnapshotErrors,
  ApiSnapshotListData,
  ApiSnapshotListResponses,
  ApiSnapshotResponses,
  ApiSnapshotSaveByIdData,
  ApiSnapshotSaveByIdErrors,
  ApiSnapshotSaveByIdResponses,
  ApiSnapshotSaveData,
  ApiSnapshotSaveErrors,
  ApiSnapshotSaveResponses,
  CatchAllData,
  CatchAllErrors,
  CatchAllResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Api Chain
 *
 * Returns the full chain tree for the timeline view.
 */
export const apiChain = <ThrowOnError extends boolean = false>(
  options?: Options<ApiChainData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ApiChainResponses, unknown, ThrowOnError>({
    url: "/api/chain",
    ...options,
  });

/**
 * Api Snapshot List
 *
 * Returns a list of all snapshots with player counts.
 */
export const apiSnapshotList = <ThrowOnError extends boolean = false>(
  options?: Options<ApiSnapshotListData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ApiSnapshotListResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/snapshot", ...options });

/**
 * Api Create Snapshot Root
 *
 * Creates a new snapshot. If parent_id is provided, links to parent via event.
 * Returns: {"snapshot_id": <new_id>}
 */
export const apiCreateSnapshotRoot = <ThrowOnError extends boolean = false>(
  options: Options<ApiCreateSnapshotRootData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiCreateSnapshotRootResponses,
    ApiCreateSnapshotRootErrors,
    ThrowOnError
  >({
    url: "/api/snapshot",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Delete Snapshot
 *
 * Deletes a snapshot and all its dependent snapshots/events.
 */
export const apiDeleteSnapshot = <ThrowOnError extends boolean = false>(
  options: Options<ApiDeleteSnapshotData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ApiDeleteSnapshotResponses,
    ApiDeleteSnapshotErrors,
    ThrowOnError
  >({ url: "/api/snapshot/{snapshot_id}", ...options });

/**
 * Api Snapshot
 *
 * Returns snapshot metadata + player list for the detail panel.
 */
export const apiSnapshot = <ThrowOnError extends boolean = false>(
  options: Options<ApiSnapshotData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiSnapshotResponses,
    ApiSnapshotErrors,
    ThrowOnError
  >({ url: "/api/snapshot/{snapshot_id}", ...options });

/**
 * Api Create Snapshot
 *
 * Creates a new root 'manual' snapshot (no source snapshot).
 * Returns: {"snapshot_id": <new_id>}
 */
export const apiCreateSnapshot = <ThrowOnError extends boolean = false>(
  options: Options<ApiCreateSnapshotData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiCreateSnapshotResponses,
    ApiCreateSnapshotErrors,
    ThrowOnError
  >({
    url: "/api/snapshot/new",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Snapshot Save By Id
 *
 * Save/update a snapshot's players and metadata by ID.
 * Returns: {"snapshot_id": <id>}
 */
export const apiSnapshotSaveById = <ThrowOnError extends boolean = false>(
  options: Options<ApiSnapshotSaveByIdData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiSnapshotSaveByIdResponses,
    ApiSnapshotSaveByIdErrors,
    ThrowOnError
  >({
    url: "/api/snapshot/{snapshot_id}/save",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Snapshot Save
 *
 * Unified endpoint to save a new snapshot from a player list.
 * Returns: {"snapshot_id": <new_id>}
 */
export const apiSnapshotSave = <ThrowOnError extends boolean = false>(
  options: Options<ApiSnapshotSaveData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiSnapshotSaveResponses,
    ApiSnapshotSaveErrors,
    ThrowOnError
  >({
    url: "/api/snapshot/save",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Add Player
 *
 * Add a player to a snapshot.
 */
export const apiAddPlayer = <ThrowOnError extends boolean = false>(
  options: Options<ApiAddPlayerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiAddPlayerResponses,
    ApiAddPlayerErrors,
    ThrowOnError
  >({
    url: "/api/snapshot/{snapshot_id}/add-player",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Notion Fetch
 *
 * Fetches raw player data from the local notion_cache table.
 * Returns: {"players": [...], "similar_names": [...], "last_updated": "..."}
 */
export const apiNotionFetch = <ThrowOnError extends boolean = false>(
  options: Options<ApiNotionFetchData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiNotionFetchResponses,
    ApiNotionFetchErrors,
    ThrowOnError
  >({
    url: "/api/snapshot/notion/fetch",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Game
 *
 * Returns full game event detail for the detail panel.
 */
export const apiGame = <ThrowOnError extends boolean = false>(
  options: Options<ApiGameData, ThrowOnError>,
) =>
  (options.client ?? client).get<ApiGameResponses, ApiGameErrors, ThrowOnError>(
    { url: "/api/game/{game_event_id}", ...options },
  );

/**
 * Api Game Delete
 *
 * Delete a game and its output snapshot, with optional squash on parent.
 */
export const apiGameDelete = <ThrowOnError extends boolean = false>(
  options: Options<ApiGameDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ApiGameDeleteResponses,
    ApiGameDeleteErrors,
    ThrowOnError
  >({ url: "/api/game/{game_id}", ...options });

/**
 * Api Game Draft
 *
 * Generates a draft of game tables without saving to the database.
 * Returns: DraftResult as dict
 */
export const apiGameDraft = <ThrowOnError extends boolean = false>(
  options: Options<ApiGameDraftData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiGameDraftResponses,
    ApiGameDraftErrors,
    ThrowOnError
  >({
    url: "/api/game/draft",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Game Save
 *
 * Saves a confirmed game draft to the database.
 * Supports both creating new games and updating existing games in-place.
 * Returns: {"game_id": int}
 */
export const apiGameSave = <ThrowOnError extends boolean = false>(
  options: Options<ApiGameSaveData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiGameSaveResponses,
    ApiGameSaveErrors,
    ThrowOnError
  >({
    url: "/api/game/save",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Run
 *
 * Runs a background script (e.g., notion_sync).
 */
export const apiRun = <ThrowOnError extends boolean = false>(
  options: Options<ApiRunData, ThrowOnError>,
) =>
  (options.client ?? client).post<ApiRunResponses, ApiRunErrors, ThrowOnError>({
    url: "/api/game/run/{script}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Player Rename
 *
 * Rename a player in the players table.
 * Returns: {"success": true} or error
 */
export const apiPlayerRename = <ThrowOnError extends boolean = false>(
  options: Options<ApiPlayerRenameData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiPlayerRenameResponses,
    ApiPlayerRenameErrors,
    ThrowOnError
  >({
    url: "/api/player/rename",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Player Get All
 *
 * Get all known players. Returns rich, unformatted objects to power UI autocomplete.
 */
export const apiPlayerGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<ApiPlayerGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ApiPlayerGetAllResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/player/all", ...options });

/**
 * Api Player Lookup
 *
 * Targeted deep history lookup. Prioritizes notion_id if provided.
 */
export const apiPlayerLookup = <ThrowOnError extends boolean = false>(
  options: Options<ApiPlayerLookupData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiPlayerLookupResponses,
    ApiPlayerLookupErrors,
    ThrowOnError
  >({
    url: "/api/player/lookup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Player Check Similarity
 *
 * Checks a list of names for typos against the NotionCache.
 */
export const apiPlayerCheckSimilarity = <ThrowOnError extends boolean = false>(
  options: Options<ApiPlayerCheckSimilarityData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiPlayerCheckSimilarityResponses,
    ApiPlayerCheckSimilarityErrors,
    ThrowOnError
  >({
    url: "/api/player/check-similarity",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Api Run Notion Sync
 *
 * Enqueues notion_sync to run in the background.
 * Returns immediately with success message.
 */
export const apiRunNotionSync = <ThrowOnError extends boolean = false>(
  options: Options<ApiRunNotionSyncData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRunNotionSyncResponses,
    ApiRunNotionSyncErrors,
    ThrowOnError
  >({
    url: "/api/run/notion_sync",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Catch All
 *
 * Serve the Svelte SPA for any route.
 */
export const catchAll = <ThrowOnError extends boolean = false>(
  options: Options<CatchAllData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CatchAllResponses,
    CatchAllErrors,
    ThrowOnError
  >({ url: "/{full_path}", ...options });
