// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AddPlayerRequest
 */
export type AddPlayerRequest = {
  /**
   * Nombre
   */
  nombre: string;
  /**
   * Notion Id
   */
  notion_id?: string | null;
  /**
   * Notion Name
   */
  notion_name?: string | null;
  /**
   * Is New
   */
  is_new?: boolean;
  /**
   * Juegos Este Ano
   */
  juegos_este_ano?: number;
  /**
   * Has Priority
   */
  has_priority?: boolean;
  /**
   * Partidas Deseadas
   */
  partidas_deseadas?: number;
  /**
   * Partidas Gm
   */
  partidas_gm?: number;
};

/**
 * CheckSimilarityRequest
 */
export type CheckSimilarityRequest = {
  /**
   * Names
   */
  names: Array<string>;
};

/**
 * GameDraftRequest
 */
export type GameDraftRequest = {
  /**
   * Snapshot Id
   */
  snapshot_id: number;
};

/**
 * GameSaveRequest
 */
export type GameSaveRequest = {
  /**
   * Snapshot Id
   */
  snapshot_id: number;
  /**
   * Draft
   */
  draft: {
    [key: string]: unknown;
  };
  /**
   * Editing Game Id
   */
  editing_game_id?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LookupRequest
 */
export type LookupRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Notion Id
   */
  notion_id?: string | null;
  /**
   * Snapshot Id
   */
  snapshot_id?: number | null;
};

/**
 * NotionFetchRequest
 */
export type NotionFetchRequest = {
  /**
   * Snapshot Names
   */
  snapshot_names?: Array<string>;
};

/**
 * PlayerAutocompleteItem
 */
export type PlayerAutocompleteItem = {
  /**
   * Display
   */
  display: string;
  /**
   * Nombre
   */
  nombre: string;
  /**
   * Notion Id
   */
  notion_id?: string | null;
  /**
   * Notion Name
   */
  notion_name?: string | null;
  /**
   * Is Local
   */
  is_local: boolean;
  /**
   * Is Alias
   */
  is_alias: boolean;
};

/**
 * PlayerAutocompleteResponse
 */
export type PlayerAutocompleteResponse = {
  /**
   * Players
   */
  players: Array<PlayerAutocompleteItem>;
};

/**
 * PlayerCreate
 */
export type PlayerCreate = {
  /**
   * Nombre
   */
  nombre: string;
  /**
   * Notion Id
   */
  notion_id?: string | null;
  /**
   * Notion Name
   */
  notion_name?: string | null;
  /**
   * Is New
   */
  is_new?: boolean;
  /**
   * Juegos Este Ano
   */
  juegos_este_ano?: number;
  /**
   * Has Priority
   */
  has_priority?: boolean;
  /**
   * Partidas Deseadas
   */
  partidas_deseadas?: number;
  /**
   * Partidas Gm
   */
  partidas_gm?: number;
};

/**
 * PlayerHistoryItem
 */
export type PlayerHistoryItem = {
  /**
   * Source
   */
  source: "history" | "notion" | "default";
  /**
   * Is New
   */
  is_new: boolean;
  /**
   * Juegos Este Ano
   */
  juegos_este_ano: number;
  /**
   * Has Priority
   */
  has_priority: boolean;
  /**
   * Partidas Deseadas
   */
  partidas_deseadas: number;
  /**
   * Partidas Gm
   */
  partidas_gm: number;
  /**
   * Notion Id
   */
  notion_id?: string | null;
  /**
   * Notion Name
   */
  notion_name?: string | null;
};

/**
 * PlayerHistoryResponse
 */
export type PlayerHistoryResponse = {
  player: PlayerHistoryItem;
};

/**
 * PlayerSimilarityItem
 */
export type PlayerSimilarityItem = {
  /**
   * Notion Id
   */
  notion_id: string;
  /**
   * Notion Name
   */
  notion_name: string;
  /**
   * Snapshot
   */
  snapshot: string;
  /**
   * Similarity
   */
  similarity: number;
  /**
   * Match Method
   */
  match_method: string;
  /**
   * Matched Alias
   */
  matched_alias?: string | null;
  /**
   * Existing Local Name
   */
  existing_local_name?: string | null;
};

/**
 * PlayerSimilarityResponse
 */
export type PlayerSimilarityResponse = {
  /**
   * Similarities
   */
  similarities: Array<PlayerSimilarityItem>;
};

/**
 * RenameDict
 */
export type RenameDict = {
  /**
   * From
   */
  from: string;
  /**
   * To
   */
  to: string;
};

/**
 * RenameRequest
 */
export type RenameRequest = {
  /**
   * Old Name
   */
  old_name: string;
  /**
   * New Name
   */
  new_name: string;
};

/**
 * RunNotionSyncRequest
 */
export type RunNotionSyncRequest = {
  /**
   * Snapshot
   */
  snapshot?: number | null;
  /**
   * Force
   */
  force?: boolean;
  /**
   * Merges
   */
  merges?: {
    [key: string]: {
      [key: string]: string;
    };
  } | null;
};

/**
 * RunScriptRequest
 */
export type RunScriptRequest = {
  /**
   * Snapshot
   */
  snapshot?: number | null;
};

/**
 * SnapshotCreateRequest
 */
export type SnapshotCreateRequest = {
  /**
   * Source
   */
  source?: string;
  /**
   * Parent Id
   */
  parent_id?: number | null;
  /**
   * Players
   */
  players: Array<PlayerCreate>;
};

/**
 * SnapshotSaveRequest
 */
export type SnapshotSaveRequest = {
  /**
   * Parent Id
   */
  parent_id?: number | null;
  /**
   * Event Type
   */
  event_type?: string;
  /**
   * Players
   */
  players: Array<PlayerCreate>;
  /**
   * Renames
   */
  renames?: Array<RenameDict>;
};

/**
 * SuccessResponse
 */
export type SuccessResponse = {
  /**
   * Success
   */
  success: boolean;
};

/**
 * SyncResponse
 */
export type SyncResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type ApiChainData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/chain";
};

export type ApiChainResponses = {
  /**
   * Response Api Chain
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiChainResponse = ApiChainResponses[keyof ApiChainResponses];

export type ApiSnapshotListData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/snapshot";
};

export type ApiSnapshotListResponses = {
  /**
   * Response Api Snapshot List
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiSnapshotListResponse =
  ApiSnapshotListResponses[keyof ApiSnapshotListResponses];

export type ApiCreateSnapshotRootData = {
  body: SnapshotCreateRequest;
  path?: never;
  query?: never;
  url: "/api/snapshot";
};

export type ApiCreateSnapshotRootErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiCreateSnapshotRootError =
  ApiCreateSnapshotRootErrors[keyof ApiCreateSnapshotRootErrors];

export type ApiCreateSnapshotRootResponses = {
  /**
   * Response Api Create Snapshot Root
   *
   * Successful Response
   */
  200: {
    [key: string]: number;
  };
};

export type ApiCreateSnapshotRootResponse =
  ApiCreateSnapshotRootResponses[keyof ApiCreateSnapshotRootResponses];

export type ApiDeleteSnapshotData = {
  body?: never;
  path: {
    /**
     * Snapshot Id
     */
    snapshot_id: number;
  };
  query?: never;
  url: "/api/snapshot/{snapshot_id}";
};

export type ApiDeleteSnapshotErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiDeleteSnapshotError =
  ApiDeleteSnapshotErrors[keyof ApiDeleteSnapshotErrors];

export type ApiDeleteSnapshotResponses = {
  /**
   * Response Api Delete Snapshot
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiDeleteSnapshotResponse =
  ApiDeleteSnapshotResponses[keyof ApiDeleteSnapshotResponses];

export type ApiSnapshotData = {
  body?: never;
  path: {
    /**
     * Snapshot Id
     */
    snapshot_id: number;
  };
  query?: never;
  url: "/api/snapshot/{snapshot_id}";
};

export type ApiSnapshotErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiSnapshotError = ApiSnapshotErrors[keyof ApiSnapshotErrors];

export type ApiSnapshotResponses = {
  /**
   * Response Api Snapshot
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiSnapshotResponse =
  ApiSnapshotResponses[keyof ApiSnapshotResponses];

export type ApiCreateSnapshotData = {
  body: SnapshotCreateRequest;
  path?: never;
  query?: never;
  url: "/api/snapshot/new";
};

export type ApiCreateSnapshotErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiCreateSnapshotError =
  ApiCreateSnapshotErrors[keyof ApiCreateSnapshotErrors];

export type ApiCreateSnapshotResponses = {
  /**
   * Response Api Create Snapshot
   *
   * Successful Response
   */
  200: {
    [key: string]: number;
  };
};

export type ApiCreateSnapshotResponse =
  ApiCreateSnapshotResponses[keyof ApiCreateSnapshotResponses];

export type ApiSnapshotSaveByIdData = {
  body: SnapshotCreateRequest;
  path: {
    /**
     * Snapshot Id
     */
    snapshot_id: number;
  };
  query?: never;
  url: "/api/snapshot/{snapshot_id}/save";
};

export type ApiSnapshotSaveByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiSnapshotSaveByIdError =
  ApiSnapshotSaveByIdErrors[keyof ApiSnapshotSaveByIdErrors];

export type ApiSnapshotSaveByIdResponses = {
  /**
   * Response Api Snapshot Save By Id
   *
   * Successful Response
   */
  200: {
    [key: string]: number;
  };
};

export type ApiSnapshotSaveByIdResponse =
  ApiSnapshotSaveByIdResponses[keyof ApiSnapshotSaveByIdResponses];

export type ApiSnapshotSaveData = {
  body: SnapshotSaveRequest;
  path?: never;
  query?: never;
  url: "/api/snapshot/save";
};

export type ApiSnapshotSaveErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiSnapshotSaveError =
  ApiSnapshotSaveErrors[keyof ApiSnapshotSaveErrors];

export type ApiSnapshotSaveResponses = {
  /**
   * Response Api Snapshot Save
   *
   * Successful Response
   */
  200: {
    [key: string]: number | string;
  };
};

export type ApiSnapshotSaveResponse =
  ApiSnapshotSaveResponses[keyof ApiSnapshotSaveResponses];

export type ApiAddPlayerData = {
  body: AddPlayerRequest;
  path: {
    /**
     * Snapshot Id
     */
    snapshot_id: number;
  };
  query?: never;
  url: "/api/snapshot/{snapshot_id}/add-player";
};

export type ApiAddPlayerErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiAddPlayerError = ApiAddPlayerErrors[keyof ApiAddPlayerErrors];

export type ApiAddPlayerResponses = {
  /**
   * Response Api Add Player
   *
   * Successful Response
   */
  200: {
    [key: string]: number;
  };
};

export type ApiAddPlayerResponse =
  ApiAddPlayerResponses[keyof ApiAddPlayerResponses];

export type ApiNotionFetchData = {
  body: NotionFetchRequest;
  path?: never;
  query?: never;
  url: "/api/snapshot/notion/fetch";
};

export type ApiNotionFetchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiNotionFetchError =
  ApiNotionFetchErrors[keyof ApiNotionFetchErrors];

export type ApiNotionFetchResponses = {
  /**
   * Response Api Notion Fetch
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiNotionFetchResponse =
  ApiNotionFetchResponses[keyof ApiNotionFetchResponses];

export type ApiGameData = {
  body?: never;
  path: {
    /**
     * Game Event Id
     */
    game_event_id: number;
  };
  query?: never;
  url: "/api/game/{game_event_id}";
};

export type ApiGameErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiGameError = ApiGameErrors[keyof ApiGameErrors];

export type ApiGameResponses = {
  /**
   * Response Api Game
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiGameResponse = ApiGameResponses[keyof ApiGameResponses];

export type ApiGameDeleteData = {
  body?: never;
  path: {
    /**
     * Game Id
     */
    game_id: number;
  };
  query?: never;
  url: "/api/game/{game_id}";
};

export type ApiGameDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiGameDeleteError = ApiGameDeleteErrors[keyof ApiGameDeleteErrors];

export type ApiGameDeleteResponses = {
  /**
   * Response Api Game Delete
   *
   * Successful Response
   */
  200: {
    [key: string]: boolean;
  };
};

export type ApiGameDeleteResponse =
  ApiGameDeleteResponses[keyof ApiGameDeleteResponses];

export type ApiGameDraftData = {
  body: GameDraftRequest;
  path?: never;
  query?: never;
  url: "/api/game/draft";
};

export type ApiGameDraftErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiGameDraftError = ApiGameDraftErrors[keyof ApiGameDraftErrors];

export type ApiGameDraftResponses = {
  /**
   * Response Api Game Draft
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiGameDraftResponse =
  ApiGameDraftResponses[keyof ApiGameDraftResponses];

export type ApiGameSaveData = {
  body: GameSaveRequest;
  path?: never;
  query?: never;
  url: "/api/game/save";
};

export type ApiGameSaveErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiGameSaveError = ApiGameSaveErrors[keyof ApiGameSaveErrors];

export type ApiGameSaveResponses = {
  /**
   * Response Api Game Save
   *
   * Successful Response
   */
  200: {
    [key: string]: number;
  };
};

export type ApiGameSaveResponse =
  ApiGameSaveResponses[keyof ApiGameSaveResponses];

export type ApiRunData = {
  body: RunScriptRequest;
  path: {
    /**
     * Script
     */
    script: string;
  };
  query?: never;
  url: "/api/game/run/{script}";
};

export type ApiRunErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiRunError = ApiRunErrors[keyof ApiRunErrors];

export type ApiRunResponses = {
  /**
   * Response Api Run
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ApiRunResponse = ApiRunResponses[keyof ApiRunResponses];

export type ApiPlayerRenameData = {
  body: RenameRequest;
  path?: never;
  query?: never;
  url: "/api/player/rename";
};

export type ApiPlayerRenameErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiPlayerRenameError =
  ApiPlayerRenameErrors[keyof ApiPlayerRenameErrors];

export type ApiPlayerRenameResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type ApiPlayerRenameResponse =
  ApiPlayerRenameResponses[keyof ApiPlayerRenameResponses];

export type ApiPlayerGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/player/all";
};

export type ApiPlayerGetAllResponses = {
  /**
   * Successful Response
   */
  200: PlayerAutocompleteResponse;
};

export type ApiPlayerGetAllResponse =
  ApiPlayerGetAllResponses[keyof ApiPlayerGetAllResponses];

export type ApiPlayerLookupData = {
  body: LookupRequest;
  path?: never;
  query?: never;
  url: "/api/player/lookup";
};

export type ApiPlayerLookupErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiPlayerLookupError =
  ApiPlayerLookupErrors[keyof ApiPlayerLookupErrors];

export type ApiPlayerLookupResponses = {
  /**
   * Successful Response
   */
  200: PlayerHistoryResponse;
};

export type ApiPlayerLookupResponse =
  ApiPlayerLookupResponses[keyof ApiPlayerLookupResponses];

export type ApiPlayerCheckSimilarityData = {
  body: CheckSimilarityRequest;
  path?: never;
  query?: never;
  url: "/api/player/check-similarity";
};

export type ApiPlayerCheckSimilarityErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiPlayerCheckSimilarityError =
  ApiPlayerCheckSimilarityErrors[keyof ApiPlayerCheckSimilarityErrors];

export type ApiPlayerCheckSimilarityResponses = {
  /**
   * Successful Response
   */
  200: PlayerSimilarityResponse;
};

export type ApiPlayerCheckSimilarityResponse =
  ApiPlayerCheckSimilarityResponses[keyof ApiPlayerCheckSimilarityResponses];

export type ApiRunNotionSyncData = {
  body: RunNotionSyncRequest;
  path?: never;
  query?: never;
  url: "/api/run/notion_sync";
};

export type ApiRunNotionSyncErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApiRunNotionSyncError =
  ApiRunNotionSyncErrors[keyof ApiRunNotionSyncErrors];

export type ApiRunNotionSyncResponses = {
  /**
   * Successful Response
   */
  200: SyncResponse;
};

export type ApiRunNotionSyncResponse =
  ApiRunNotionSyncResponses[keyof ApiRunNotionSyncResponses];

export type CatchAllData = {
  body?: never;
  path?: never;
  query: {
    /**
     *  Full Path
     */
    _full_path: string;
  };
  url: "/{full_path}";
};

export type CatchAllErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CatchAllError = CatchAllErrors[keyof CatchAllErrors];

export type CatchAllResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
