// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Branch
 */
export type Branch = {
    edge: ChainEdge;
    output?: SnapshotNode | null;
};

/**
 * ChainEdge
 */
export type ChainEdge = {
    /**
     * Id
     */
    id: number;
    /**
     * Type
     */
    type: 'sync' | 'game' | 'edit' | 'branch';
    /**
     * Created At
     */
    created_at: string | string;
    /**
     * From Id
     */
    from_id: number;
    /**
     * To Id
     */
    to_id?: number | null;
    /**
     * Intentos
     */
    intentos?: number | null;
    /**
     * Mesa Count
     */
    mesa_count?: number | null;
    /**
     * Espera Count
     */
    espera_count?: number | null;
};

/**
 * ChainResponse
 */
export type ChainResponse = {
    /**
     * Roots
     */
    roots: Array<SnapshotNode>;
};

/**
 * CheckSimilarityRequest
 */
export type CheckSimilarityRequest = {
    /**
     * Names
     */
    names: Array<string>;
};

/**
 * CountrySelection
 */
export type CountrySelection = {
    /**
     * Name
     */
    name: string;
    /**
     * Reason
     */
    reason?: Array<string>;
};

/**
 * DeepDiffResult
 */
export type DeepDiffResult = {
    /**
     * Added
     */
    added: Array<string>;
    /**
     * Removed
     */
    removed: Array<string>;
    /**
     * Renamed
     */
    renamed: Array<RenameChange>;
    /**
     * Modified
     */
    modified: Array<ModifiedPlayer>;
};

/**
 * DeleteResponse
 *
 * Response model for delete operations.
 */
export type DeleteResponse = {
    /**
     * Deleted
     */
    deleted: number;
};

/**
 * ErrorMessage
 */
export type ErrorMessage = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * FieldChange
 */
export type FieldChange = {
    old: FieldValue;
    new: FieldValue;
};

/**
 * FieldValue
 */
export type FieldValue = string | number | boolean | Array<string> | null;

/**
 * GameDetailResponse
 */
export type GameDetailResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | string;
    /**
     * Intentos
     */
    intentos: number;
    /**
     * Mesas
     */
    mesas: Array<GameDraftTableOutput>;
    /**
     * Waiting List
     */
    waiting_list: Array<GameDraftPlayer>;
    /**
     * Input Snapshot Id
     */
    input_snapshot_id?: number | null;
    /**
     * Output Snapshot Id
     */
    output_snapshot_id?: number | null;
};

/**
 * GameDraftPlayer
 */
export type GameDraftPlayer = {
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Is New
     */
    is_new: boolean;
    /**
     * Juegos Este Ano
     */
    juegos_este_ano: number;
    /**
     * Has Priority
     */
    has_priority: boolean;
    /**
     * Partidas Deseadas
     */
    partidas_deseadas: number;
    /**
     * Partidas Gm
     */
    partidas_gm: number;
    /**
     * C England
     */
    c_england: number;
    /**
     * C France
     */
    c_france: number;
    /**
     * C Germany
     */
    c_germany: number;
    /**
     * C Italy
     */
    c_italy: number;
    /**
     * C Austria
     */
    c_austria: number;
    /**
     * C Russia
     */
    c_russia: number;
    /**
     * C Turkey
     */
    c_turkey: number;
    country: CountrySelection;
    /**
     * Cupos Faltantes
     */
    cupos_faltantes: number;
};

/**
 * GameDraftRequest
 */
export type GameDraftRequest = {
    /**
     * Snapshot Id
     */
    snapshot_id: number;
};

/**
 * GameDraftResponse
 */
export type GameDraftResponseInput = {
    /**
     * Mesas
     */
    mesas: Array<GameDraftTableInput>;
    /**
     * Tickets Sobrantes
     */
    tickets_sobrantes: Array<GameDraftPlayer>;
    /**
     * Minimo Teorico
     */
    minimo_teorico: number;
    /**
     * Intentos Usados
     */
    intentos_usados: number;
};

/**
 * GameDraftResponse
 */
export type GameDraftResponseOutput = {
    /**
     * Mesas
     */
    mesas: Array<GameDraftTableOutput>;
    /**
     * Tickets Sobrantes
     */
    tickets_sobrantes: Array<GameDraftPlayer>;
    /**
     * Minimo Teorico
     */
    minimo_teorico: number;
    /**
     * Intentos Usados
     */
    intentos_usados: number;
};

/**
 * GameDraftTable
 */
export type GameDraftTableInput = {
    /**
     * Numero
     */
    numero: number;
    gm?: GameDraftPlayer | null;
    /**
     * Jugadores
     */
    jugadores: Array<GameDraftPlayer>;
};

/**
 * GameDraftTable
 */
export type GameDraftTableOutput = {
    /**
     * Numero
     */
    numero: number;
    gm?: GameDraftPlayer | null;
    /**
     * Jugadores
     */
    jugadores: Array<GameDraftPlayer>;
};

/**
 * GameSaveRequest
 */
export type GameSaveRequest = {
    /**
     * Snapshot Id
     */
    snapshot_id: number;
    draft: GameDraftResponseInput;
    /**
     * Editing Game Id
     */
    editing_game_id?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HistoryEntry
 *
 * History entry for snapshot changes.
 */
export type HistoryEntry = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Action Type
     */
    action_type: string;
    changes: DeepDiffResult;
};

/**
 * LookupRequest
 */
export type LookupRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Notion Id
     */
    notion_id?: string | null;
    /**
     * Snapshot Id
     */
    snapshot_id?: number | null;
};

/**
 * ModifiedPlayer
 */
export type ModifiedPlayer = {
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Changes
     */
    changes: {
        [key: string]: FieldChange;
    };
};

/**
 * NotionFetchRequest
 */
export type NotionFetchRequest = {
    /**
     * Snapshot Names
     */
    snapshot_names?: Array<string>;
};

/**
 * NotionFetchResponse
 *
 * Response model for POST /api/snapshot/notion/fetch endpoint.
 */
export type NotionFetchResponse = {
    /**
     * Players
     */
    players: Array<NotionPlayerData>;
    /**
     * Similar Names
     */
    similar_names: Array<SimilarName>;
    /**
     * Last Updated
     */
    last_updated: string | null;
};

/**
 * NotionPlayerData
 *
 * Player data from Notion cache.
 */
export type NotionPlayerData = {
    /**
     * Notion Id
     */
    notion_id: string;
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Is New
     */
    is_new: boolean;
    /**
     * Juegos Este Ano
     */
    juegos_este_ano: number;
    /**
     * C England
     */
    c_england: number;
    /**
     * C France
     */
    c_france: number;
    /**
     * C Germany
     */
    c_germany: number;
    /**
     * C Italy
     */
    c_italy: number;
    /**
     * C Austria
     */
    c_austria: number;
    /**
     * C Russia
     */
    c_russia: number;
    /**
     * C Turkey
     */
    c_turkey: number;
    /**
     * Alias
     */
    alias?: Array<string> | null;
};

/**
 * PlayerAutocompleteItem
 */
export type PlayerAutocompleteItem = {
    /**
     * Display
     */
    display: string;
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Notion Id
     */
    notion_id?: string | null;
    /**
     * Notion Name
     */
    notion_name?: string | null;
    /**
     * Is Local
     */
    is_local: boolean;
    /**
     * Is Alias
     */
    is_alias: boolean;
};

/**
 * PlayerAutocompleteResponse
 */
export type PlayerAutocompleteResponse = {
    /**
     * Players
     */
    players: Array<PlayerAutocompleteItem>;
};

/**
 * PlayerCreate
 */
export type PlayerCreate = {
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Notion Id
     */
    notion_id?: string | null;
    /**
     * Notion Name
     */
    notion_name?: string | null;
    /**
     * Is New
     */
    is_new?: boolean;
    /**
     * Juegos Este Ano
     */
    juegos_este_ano?: number;
    /**
     * Has Priority
     */
    has_priority?: boolean;
    /**
     * Partidas Deseadas
     */
    partidas_deseadas?: number;
    /**
     * Partidas Gm
     */
    partidas_gm?: number;
};

/**
 * PlayerData
 *
 * Player data within a snapshot.
 */
export type PlayerData = {
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Notion Id
     */
    notion_id: string | null;
    /**
     * Notion Name
     */
    notion_name: string | null;
    /**
     * Is New
     */
    is_new: boolean;
    /**
     * Juegos Este Ano
     */
    juegos_este_ano: number;
    /**
     * Has Priority
     */
    has_priority: boolean;
    /**
     * Partidas Deseadas
     */
    partidas_deseadas: number;
    /**
     * Partidas Gm
     */
    partidas_gm: number;
    /**
     * C England
     */
    c_england: number;
    /**
     * C France
     */
    c_france: number;
    /**
     * C Germany
     */
    c_germany: number;
    /**
     * C Italy
     */
    c_italy: number;
    /**
     * C Austria
     */
    c_austria: number;
    /**
     * C Russia
     */
    c_russia: number;
    /**
     * C Turkey
     */
    c_turkey: number;
    /**
     * Alias
     */
    alias: string | null;
};

/**
 * PlayerHistoryItem
 */
export type PlayerHistoryItem = {
    /**
     * Source
     */
    source: 'history' | 'notion' | 'default';
    /**
     * Is New
     */
    is_new: boolean;
    /**
     * Juegos Este Ano
     */
    juegos_este_ano: number;
    /**
     * Has Priority
     */
    has_priority: boolean;
    /**
     * Partidas Deseadas
     */
    partidas_deseadas: number;
    /**
     * Partidas Gm
     */
    partidas_gm: number;
    /**
     * Notion Id
     */
    notion_id?: string | null;
    /**
     * Notion Name
     */
    notion_name?: string | null;
};

/**
 * PlayerHistoryResponse
 */
export type PlayerHistoryResponse = {
    player: PlayerHistoryItem;
};

/**
 * PlayerSimilarityItem
 */
export type PlayerSimilarityItem = {
    /**
     * Notion Id
     */
    notion_id: string;
    /**
     * Notion Name
     */
    notion_name: string;
    /**
     * Snapshot
     */
    snapshot: string;
    /**
     * Similarity
     */
    similarity: number;
    /**
     * Match Method
     */
    match_method: string;
    /**
     * Matched Alias
     */
    matched_alias?: string | null;
    /**
     * Existing Local Name
     */
    existing_local_name?: string | null;
};

/**
 * PlayerSimilarityResponse
 */
export type PlayerSimilarityResponse = {
    /**
     * Similarities
     */
    similarities: Array<PlayerSimilarityItem>;
};

/**
 * RenameChange
 */
export type RenameChange = {
    /**
     * Old Name
     */
    old_name: string;
    /**
     * New Name
     */
    new_name: string;
};

/**
 * RenameRequest
 */
export type RenameRequest = {
    /**
     * Old Name
     */
    old_name: string;
    /**
     * New Name
     */
    new_name: string;
};

/**
 * RunNotionSyncRequest
 */
export type RunNotionSyncRequest = {
    /**
     * Snapshot
     */
    snapshot?: number | null;
    /**
     * Force
     */
    force?: boolean;
    /**
     * Merges
     */
    merges?: {
        [key: string]: {
            [key: string]: string;
        };
    } | null;
};

/**
 * SimilarName
 *
 * Similar name detection result.
 */
export type SimilarName = {
    /**
     * Notion Id
     */
    notion_id: string;
    /**
     * Notion Name
     */
    notion_name: string;
    /**
     * Snapshot
     */
    snapshot: string;
    /**
     * Similarity
     */
    similarity: number;
    /**
     * Match Method
     */
    match_method: string;
    /**
     * Matched Alias
     */
    matched_alias?: string | null;
    /**
     * Existing Local Name
     */
    existing_local_name?: string | null;
};

/**
 * SnapshotDetailResponse
 *
 * Response model for GET /api/snapshot/{id} endpoint.
 */
export type SnapshotDetailResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    source: SnapshotSource;
    /**
     * Players
     */
    players: Array<PlayerData>;
    /**
     * History
     */
    history: Array<HistoryEntry>;
};

/**
 * SnapshotNode
 */
export type SnapshotNode = {
    /**
     * Type
     */
    type: 'snapshot';
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | string;
    source: SnapshotSource;
    /**
     * Player Count
     */
    player_count: number;
    /**
     * Is Latest
     */
    is_latest: boolean;
    /**
     * Branches
     */
    branches: Array<Branch>;
};

/**
 * SnapshotSaveEventType
 */
export type SnapshotSaveEventType = 'manual' | 'sync';

/**
 * SnapshotSaveRequest
 */
export type SnapshotSaveRequest = {
    /**
     * Parent Id
     */
    parent_id?: number | null;
    event_type?: SnapshotSaveEventType;
    /**
     * Players
     */
    players: Array<PlayerCreate>;
    /**
     * Renames
     */
    renames?: Array<RenameChange>;
};

/**
 * SnapshotSaveResponse
 *
 * Response model for snapshot save operations.
 */
export type SnapshotSaveResponse = {
    /**
     * Snapshot Id
     */
    snapshot_id: number;
    /**
     * Status
     */
    status?: string | null;
};

/**
 * SnapshotSource
 */
export type SnapshotSource = 'manual' | 'manual_edit' | 'notion_sync' | 'organizar';

/**
 * SuccessResponse
 */
export type SuccessResponse = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * SyncResponse
 */
export type SyncResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * SyncStatusResponse
 */
export type SyncStatusResponse = {
    /**
     * Status
     */
    status: 'pending' | 'syncing' | 'ready' | 'unconfigured' | 'error';
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ApiChainData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chain';
};

export type ApiChainErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiChainError = ApiChainErrors[keyof ApiChainErrors];

export type ApiChainResponses = {
    /**
     * Successful Response
     */
    200: ChainResponse;
};

export type ApiChainResponse = ApiChainResponses[keyof ApiChainResponses];

export type ApiDeleteSnapshotData = {
    body?: never;
    path: {
        /**
         * Snapshot Id
         */
        snapshot_id: number;
    };
    query?: never;
    url: '/api/snapshot/{snapshot_id}';
};

export type ApiDeleteSnapshotErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiDeleteSnapshotError = ApiDeleteSnapshotErrors[keyof ApiDeleteSnapshotErrors];

export type ApiDeleteSnapshotResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type ApiDeleteSnapshotResponse = ApiDeleteSnapshotResponses[keyof ApiDeleteSnapshotResponses];

export type ApiSnapshotData = {
    body?: never;
    path: {
        /**
         * Snapshot Id
         */
        snapshot_id: number;
    };
    query?: never;
    url: '/api/snapshot/{snapshot_id}';
};

export type ApiSnapshotErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiSnapshotError = ApiSnapshotErrors[keyof ApiSnapshotErrors];

export type ApiSnapshotResponses = {
    /**
     * Successful Response
     */
    200: SnapshotDetailResponse;
};

export type ApiSnapshotResponse = ApiSnapshotResponses[keyof ApiSnapshotResponses];

export type ApiSnapshotSaveData = {
    body: SnapshotSaveRequest;
    path?: never;
    query?: never;
    url: '/api/snapshot/save';
};

export type ApiSnapshotSaveErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiSnapshotSaveError = ApiSnapshotSaveErrors[keyof ApiSnapshotSaveErrors];

export type ApiSnapshotSaveResponses = {
    /**
     * Successful Response
     */
    200: SnapshotSaveResponse;
};

export type ApiSnapshotSaveResponse = ApiSnapshotSaveResponses[keyof ApiSnapshotSaveResponses];

export type ApiNotionFetchData = {
    body: NotionFetchRequest;
    path?: never;
    query?: never;
    url: '/api/snapshot/notion/fetch';
};

export type ApiNotionFetchErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiNotionFetchError = ApiNotionFetchErrors[keyof ApiNotionFetchErrors];

export type ApiNotionFetchResponses = {
    /**
     * Successful Response
     */
    200: NotionFetchResponse;
};

export type ApiNotionFetchResponse = ApiNotionFetchResponses[keyof ApiNotionFetchResponses];

export type ApiGameData = {
    body?: never;
    path: {
        /**
         * Game Event Id
         */
        game_event_id: number;
    };
    query?: never;
    url: '/api/game/{game_event_id}';
};

export type ApiGameErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiGameError = ApiGameErrors[keyof ApiGameErrors];

export type ApiGameResponses = {
    /**
     * Successful Response
     */
    200: GameDetailResponse;
};

export type ApiGameResponse = ApiGameResponses[keyof ApiGameResponses];

export type ApiGameDeleteData = {
    body?: never;
    path: {
        /**
         * Game Id
         */
        game_id: number;
    };
    query?: never;
    url: '/api/game/{game_id}';
};

export type ApiGameDeleteErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiGameDeleteError = ApiGameDeleteErrors[keyof ApiGameDeleteErrors];

export type ApiGameDeleteResponses = {
    /**
     * Response Api Game Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type ApiGameDeleteResponse = ApiGameDeleteResponses[keyof ApiGameDeleteResponses];

export type ApiGameDraftData = {
    body: GameDraftRequest;
    path?: never;
    query?: never;
    url: '/api/game/draft';
};

export type ApiGameDraftErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiGameDraftError = ApiGameDraftErrors[keyof ApiGameDraftErrors];

export type ApiGameDraftResponses = {
    /**
     * Successful Response
     */
    200: GameDraftResponseOutput;
};

export type ApiGameDraftResponse = ApiGameDraftResponses[keyof ApiGameDraftResponses];

export type ApiGameSaveData = {
    body: GameSaveRequest;
    path?: never;
    query?: never;
    url: '/api/game/save';
};

export type ApiGameSaveErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiGameSaveError = ApiGameSaveErrors[keyof ApiGameSaveErrors];

export type ApiGameSaveResponses = {
    /**
     * Response Api Game Save
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type ApiGameSaveResponse = ApiGameSaveResponses[keyof ApiGameSaveResponses];

export type ApiPlayerRenameData = {
    body: RenameRequest;
    path?: never;
    query?: never;
    url: '/api/player/rename';
};

export type ApiPlayerRenameErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiPlayerRenameError = ApiPlayerRenameErrors[keyof ApiPlayerRenameErrors];

export type ApiPlayerRenameResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type ApiPlayerRenameResponse = ApiPlayerRenameResponses[keyof ApiPlayerRenameResponses];

export type ApiPlayerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/player/all';
};

export type ApiPlayerGetAllErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiPlayerGetAllError = ApiPlayerGetAllErrors[keyof ApiPlayerGetAllErrors];

export type ApiPlayerGetAllResponses = {
    /**
     * Successful Response
     */
    200: PlayerAutocompleteResponse;
};

export type ApiPlayerGetAllResponse = ApiPlayerGetAllResponses[keyof ApiPlayerGetAllResponses];

export type ApiPlayerLookupData = {
    body: LookupRequest;
    path?: never;
    query?: never;
    url: '/api/player/lookup';
};

export type ApiPlayerLookupErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiPlayerLookupError = ApiPlayerLookupErrors[keyof ApiPlayerLookupErrors];

export type ApiPlayerLookupResponses = {
    /**
     * Successful Response
     */
    200: PlayerHistoryResponse;
};

export type ApiPlayerLookupResponse = ApiPlayerLookupResponses[keyof ApiPlayerLookupResponses];

export type ApiPlayerCheckSimilarityData = {
    body: CheckSimilarityRequest;
    path?: never;
    query?: never;
    url: '/api/player/check-similarity';
};

export type ApiPlayerCheckSimilarityErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiPlayerCheckSimilarityError = ApiPlayerCheckSimilarityErrors[keyof ApiPlayerCheckSimilarityErrors];

export type ApiPlayerCheckSimilarityResponses = {
    /**
     * Successful Response
     */
    200: PlayerSimilarityResponse;
};

export type ApiPlayerCheckSimilarityResponse = ApiPlayerCheckSimilarityResponses[keyof ApiPlayerCheckSimilarityResponses];

export type ApiRunNotionSyncData = {
    body: RunNotionSyncRequest;
    path?: never;
    query?: never;
    url: '/api/run/notion_sync';
};

export type ApiRunNotionSyncErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiRunNotionSyncError = ApiRunNotionSyncErrors[keyof ApiRunNotionSyncErrors];

export type ApiRunNotionSyncResponses = {
    /**
     * Successful Response
     */
    200: SyncResponse;
};

export type ApiRunNotionSyncResponse = ApiRunNotionSyncResponses[keyof ApiRunNotionSyncResponses];

export type ApiSyncStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sync/status';
};

export type ApiSyncStatusErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type ApiSyncStatusError = ApiSyncStatusErrors[keyof ApiSyncStatusErrors];

export type ApiSyncStatusResponses = {
    /**
     * Successful Response
     */
    200: SyncStatusResponse;
};

export type ApiSyncStatusResponse = ApiSyncStatusResponses[keyof ApiSyncStatusResponses];

export type CatchAllData = {
    body?: never;
    path?: never;
    query: {
        /**
         *  Full Path
         */
        _full_path: string;
    };
    url: '/{full_path}';
};

export type CatchAllErrors = {
    /**
     * Client Error
     */
    400: ErrorMessage;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server Error
     */
    500: ErrorMessage;
};

export type CatchAllError = CatchAllErrors[keyof CatchAllErrors];

export type CatchAllResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
